#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the largestRectangle function below.
def largestRectangle(h):
    
    maxx=0
    for i in range(len(h)):
      c=1
      for j in range(i+1,len(h)):
          if h[j]>=h[i]:
            c+=1
          else:
            break
      for m in range(i-1,-1,-1):
        if h[m]>= h[i]:
          c+=1
        else:
          break
      x=h[i]*c
      print(x)
      if x>maxx:
        maxx=x
    return maxx



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    h = list(map(int, input().rstrip().split()))

    result = largestRectangle(h)

    fptr.write(str(result) + '\n')

    fptr.close()
